<template>
    <div>表格</div>
    <table>
        <tr>
            <th>xxxxxxxxxx</th>
            <th>wwwwwwwww</th>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
        <tr>
            <td>dd</td>
            <td>aa</td>
        </tr>
    </table>
    <van-pagination v-model="currentPage" :total-items="24" :items-per-page="5" />
</template>

<script>
    import { ref } from 'vue';

    export default {
        name: "TableQueryTest",
        setup() {
            const currentPage = ref(1);
            return { currentPage };
        },
    }
</script>

<style scoped>

</style>